services:
  - type: web
    name: keap-resubscribe
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 3000
